<a href="https://colab.research.google.com/github/Motley12/II/blob/main/Perimey_Workbook2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.1 Теоретический материал

NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.
Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
 pip install numpy
Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:
 import numpy as np
Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.
Наиболее важные атрибуты объектов ndarray:
ndarray.ndim - число измерений (чаще их называют "оси") массива.
ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
ndarray.size - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.
ndarray.dtype - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.
ndarray.itemsize - размер каждого элемента массива в байтах.
ndarray.data - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.

# 1.2.1 Пример

Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [ ]:
import numpy as np
x= np.array ([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print (x)
print (x[3][1])
print (x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


# 1.2.2 Пример

1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [ ]:
import numpy as np
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10, 20)
print (a, "\n",b,"\n",c,"\n",d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


# 1.2.3 Пример

Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [ ]:
import numpy as np
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print (Zmin, Zmax, Zmean)

0.012058911115634285 0.9967543530414634 0.47155625940603135


# 1.2.4 Пример

Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [ ]:
import numpy as np
A = np.arange(25).reshape(5,5)
A[[0,1]]=A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 1.2.5 Пример

Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1


In [ ]:
import numpy as np
print (0 * np.nan)
print (np.nan == np.nan)
print (np.inf > np.nan)
print (np.nan - np.nan)
print (0.3 == 3*0.1)

nan
False
False
nan
False


# 1.2.6 Пример

Отсортировать массив.

In [ ]:
import numpy as np
arr = np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


# 1.3.1 Задание

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [ ]:
import numpy as np
x = np.full((8,8),0)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 1.3.2 Задание

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [ ]:
import numpy as np
x = np.full((5,5),np.arange(5))
print (x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3 Задание

Создать массив 3x3x3 со случайными значениями.


In [ ]:
import numpy as np
Z = np.random.random((3,3,3))
print (Z)

[[[0.50428061 0.79794606 0.42331032]
  [0.25998527 0.77938287 0.60991727]
  [0.74159231 0.7187904  0.63624404]]

 [[0.55273993 0.22007382 0.41502373]
  [0.67317715 0.0272663  0.02825943]
  [0.00922521 0.57903586 0.34094811]]

 [[0.90362957 0.79200656 0.55741128]
  [0.49821634 0.52607788 0.84396649]
  [0.60323321 0.10337654 0.11327422]]]


# 1.3.4 Задание

Создать матрицу с 0 внутри, и 1 на границах.

In [ ]:
import numpy as np
x = np.full((8,8),0)
x[0::7,::1] = 1
x[::1,0::7] = 1
print(x)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


# 1.3.5 Задание

Создайте массив и отсортируйте его по убыванию.

In [ ]:
import numpy as np
arr = np.arange(10,100)
print(-np.sort(-arr))

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# 1.3.6 Задание

Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
import numpy as np
x = np.full((3,9,3),0)
print("размер    ",x.size)
print("форма     ", x.shape)
print("измерение ", x.ndim)
print (x)

размер     81
форма      (3, 9, 3)
измерение  3
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


# 2.1. Теоретический материал

Первым шагом в любом начинании в области машинного обучения
является введение исходных данных в систему. Исходные данные могут
вводиться вручную, содержаться в файле или храниться в интернете в какомлибо формате. Кроме того, часто требуется получить данные из нескольких
источников.
Библиотека pandas – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.
Библиотека pandas присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите
командной строке:
 pip install pandas
Для импорта библиотеки используйте команду:
import pandas as pd
Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.
Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.
DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами.

# 2.2.1 Пример

Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [ ]:
import pandas as pd
lst = [1,2,3,4,5]
d ={'a':1, 'b':2, 'c':3}
ndarr = np.array([1,2,3,4,5])
s1=pd.Series(lst)
s2=pd.Series(d)
s3=pd.Series(ndarr,['a','b','c','d','e'])
print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


#  2.2.2 Пример

Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [ ]:
import pandas as pd
s1=pd.Series([1,2,3,4,5],['a','b','c','d','e'])
s2=pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


# 2.2.3 Пример

Создайте новый фрейм данных.

In [ ]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон','Стивен Стивенсон']
dataframe['Возраст'] = [38,25]
dataframe['Водитель'] = [True,False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

# 2.2.4 Пример

Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

# 2.2.5 Пример

Пронализировать характеристики фрейма данных

In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [ ]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [ ]:
dataframe.shape

(1313, 6)

In [ ]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

# 2.2.6 Пример

Выберите индивидуальные данные или срезы фрейма данных

In [ ]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

# 2.2.7 Пример

Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [ ]:
dataframe[dataframe['PClass'] =='1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

# 2.3.1 Задание

Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [ ]:
import pandas as pd
import numpy as np
a = pd.Series([0, 0, 0, 0])
a = np.random.random((4))
b = pd.Series([0, 0, 0, 0])
b = np.random.random((4))
print (a,b)
c = np.power(b-a,2)
d = np.sqrt(np.sum(c))
print(d)

[0.90429647 0.12876225 0.16611345 0.51793446] [0.97839211 0.17889373 0.13705415 0.43541141]
0.12513123926675096


# 2.3.2 Задание

Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/abolone.csv'
dataframe=pd.read_csv(url)
dataframe.head(20)

# 2.3.3 Задание

Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.


In [ ]:
dataframe.tail(3)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
4174      M   0.600     0.475   0.205        1.1760          0.5255   
4175      F   0.625     0.485   0.150        1.0945          0.5310   
4176      M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
4174          0.2875         0.308      9  
4175          0.2610         0.296     10  
4176          0.3765         0.495     12

In [ ]:
dataframe.head(3)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   

   Viscera weight  Shell weight  Rings  
0          0.1010          0.15     15  
1          0.0485          0.07      7  
2          0.1415          0.21      9

In [ ]:
dataframe.shape

(4177, 9)

In [ ]:
dataframe.describe()

Length     Diameter       Height  Whole weight  Shucked weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscera weight  Shell weight        Rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  
25%          0.093500      0.130000     8.000000  
50%          0.171000      0.234000     9.000000  
75%          0.253000      0.329000    11.000000  
max          0.760000      1.005000    29.000000

In [ ]:
dataframe.iloc[10:15]

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
10      F   0.525     0.380   0.140        0.6065          0.1940   
11      M   0.430     0.350   0.110        0.4060          0.1675   
12      M   0.490     0.380   0.135        0.5415          0.2175   
13      F   0.535     0.405   0.145        0.6845          0.2725   
14      F   0.470     0.355   0.100        0.4755          0.1675   

    Viscera weight  Shell weight  Rings  
10          0.1475         0.210     14  
11          0.0810         0.135     10  
12          0.0950         0.190     11  
13          0.1710         0.205     10  
14          0.0805         0.185     10

In [ ]:
dataframe[dataframe['Length'] > 0.8].head(1)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
1428      F   0.815      0.65    0.25         2.255          0.8905   

      Viscera weight  Shell weight  Rings  
1428            0.42        0.7975     14

# 3.1. Теоретический материал

Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом
представления этих величин является численным (например, 150 студентов,
$529 392 продаж).
Нормализация данных — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. В зависимости от используемой функции, их
можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.
На практике наиболее распространены следующие методы
нормализации признаков:
 Минимакс – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;
 Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.
При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.

# 3.2.1. Пример

Прошкалируйте числовой признак в диапазон между двумя значениями.

In [ ]:
import numpy as np
from sklearn import preprocessing
feature = np.array([[-500.5],[-100.1],[0],[100.1],[900.9]])
minimax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature = minimax_scale.fit_transform(feature)
scaled_feature


array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# 3.2.2. Пример

Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [ ]:
import numpy as np
from sklearn import preprocessing
x = np.array([[-1000.1],[-200.2],[500.5],[600.6],[9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized
print('Среднее: ', round(standardized.mean()))
print('Стандартное отклонение: ',standardized.std())

Среднее:  0
Стандартное отклонение:  1.0


# 3.2.3. Пример

Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({ 'A':[14.00,90.20,90.95,96.27,91.21],
                        'B':[103.02,107.26,110.35,114.23,114.68],
                        'C':['big','small','big','small','small']})
dfTest[['A','B']]=scaler.fit_transform(dfTest[['A','B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

# 3.3.2 Задание

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
import pandas as pd
from sklearn import preprocessing
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
feature = np.array(dataframe['sepal_length_cm']).reshape(-1,1)
scaler = preprocessing.MinMaxScaler(feature)
feature

In [ ]:
feature = np.array(dataframe['sepal_width_cm']).reshape(-1,1)
scaler = preprocessing.StandardScaler()
feature = scaler.fit_transform(feature)
feature